version: "3.9"

services:
  nextjs-app:
    container_name: sumbu-labs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: ${MONGODB_URI}
        JWT_SECRET: ${JWT_SECRET}
        ADMIN_COOKIE_NAME: ${ADMIN_COOKIE_NAME:-sb_admin_token}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_COOKIE_NAME: ${ADMIN_COOKIE_NAME:-sb_admin_token}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    restart: unless-stopped
